const mongoose = require('mongoose');

const referralSchema = new mongoose.Schema(
  {
    // =========================
    // REFERRAL OWNERS
    // =========================

    referrerOwnerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Owner',
      required: true,
    },

    referredOwnerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Owner',
      required: true,
    },

    // Referral code that created this relationship.
    // This is kept permanently for history.
    referralCode: {
      type: String,
      required: true,
      trim: true,
      uppercase: true,
    },

    cycleNumber: {
      type: Number,
      required: true,
      min: 1,
      default: 1,
    },

    slotNumber: {
      type: Number,
      required: true,
      min: 1,
      max: 7,
    },

    // =========================
    // REFERRAL STATUS
    // =========================

    status: {
      type: String,
      enum: [
        'REGISTERED',
        'QUALIFYING',
        'QUALIFIED',
        'NOT_QUALIFIED',
        'FINALIZED',
        'REWARDED',
        'REJECTED',
      ],
      default: 'REGISTERED',
      index: true,
    },

    joinedAt: {
      type: Date,
      default: Date.now,
      required: true,
    },

    // =========================
    // QUALIFICATION PERIOD
    // =========================

    qualification: {
      startDate: {
        type: Date,
        required: true,
      },

      endDate: {
        type: Date,
        required: true,
      },

      requiredOrders: {
        type: Number,
        default: 100,
        min: 0,
      },

      referredOwnerOrders: {
        type: Number,
        default: 0,
        min: 0,
      },

      referrerOwnerOrders: {
        type: Number,
        default: 0,
        min: 0,
      },

      requiredActiveDays: {
        type: Number,
        default: 18,
        min: 0,
      },

      referredOwnerActiveDays: {
        type: Number,
        default: 0,
        min: 0,
      },

      referrerOwnerActiveDays: {
        type: Number,
        default: 0,
        min: 0,
      },

      qualificationDays: {
        type: Number,
        default: 20,
        min: 1,
      },

      finalizedAt: {
        type: Date,
        default: null,
      },
    },

    // =========================
    // REFERRAL EARNINGS
    // =========================

    earnings: {
      // Total RMA platform fees generated by referred shop
      rmaFeesGenerated: {
        type: Number,
        default: 0,
        min: 0,
      },

      rewardPercentage: {
        type: Number,
        default: 20,
        min: 0,
        max: 100,
      },

      calculatedReward: {
        type: Number,
        default: 0,
        min: 0,
      },

      rewardCap: {
        type: Number,
        default: 500,
        min: 0,
      },

      finalReward: {
        type: Number,
        default: 0,
        min: 0,
      },
    },

    // =========================
    // REWARD SETTLEMENT
    // =========================

    settlement: {
      status: {
        type: String,
        enum: ['NOT_READY', 'PENDING', 'COMPLETED', 'FAILED'],
        default: 'NOT_READY',
      },

      transactionId: {
        type: String,
        default: null,
        trim: true,
      },

      transferredAt: {
        type: Date,
        default: null,
      },
    },

    // =========================
    // ADMIN / FRAUD CONTROL
    // =========================

    rejectionReason: {
      type: String,
      default: null,
      trim: true,
    },

    metadata: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },
  },
  {
    timestamps: true,
  },
);

// =========================
// INDEXES
// =========================

// One referred shop can only belong to one referrer.
referralSchema.index({ referredOwnerId: 1 }, { unique: true });

// Prevent the same referrer from creating duplicate
// referral records for the same referred shop.
referralSchema.index(
  { referrerOwnerId: 1, referredOwnerId: 1 },
  { unique: true },
);

// Useful for loading an owner's referral list.
referralSchema.index({
  referrerOwnerId: 1,
  createdAt: -1,
});

referralSchema.index(
  {
    referrerOwnerId: 1,
    cycleNumber: 1,
    slotNumber: 1,
  },
  {
    unique: true,
  },
);

module.exports = mongoose.model('Referral', referralSchema);
