import './HowRmaWorks.css';

import RmaCharacter from './RmaCharacter';

function HowRmaWorks({ onClose }) {
  const steps = [
    {
      number: 1,
      title: 'Bring your shop online',
      text: 'Create your RMA shop profile, add your products, set your prices and tell customers when your shop is open.',
    },
    {
      number: 2,
      title: 'Get discovered by customers',
      text: 'Customers can discover nearby RMA shops and view your shop, products, availability and delivery options.',
    },
    {
      number: 3,
      title: 'Show your products',
      text: 'Add the products you sell with clear names, prices and availability so customers can easily choose what they need.',
    },
    {
      number: 4,
      title: 'Customers order online',
      text: 'Customers select their products, choose delivery or pickup, provide their details and place their order through RMA.',
    },
    {
      number: 5,
      title: 'Receive the order',
      text: 'Your shop receives the order and you can review the items, quantity, customer details and order type.',
    },
    {
      number: 6,
      title: 'Prepare the order',
      text: 'Prepare the customers order according to the requested products and quantities, then update the order status.',
    },
    {
      number: 7,
      title: 'Delivery or pickup',
      text: 'For delivery orders, a delivery partner can handle the journey. For pickup orders, the customer can collect the order from your shop.',
    },
    {
      number: 8,
      title: 'Customers track their order',
      text: 'Customers can follow their order status from preparation through delivery or pickup.',
    },
    {
      number: 9,
      title: 'Build your customer base',
      text: 'RMA helps your shop accept online orders so customers can continue ordering from you without needing to visit or call the shop every time.',
    },
    {
      number: 10,
      title: 'Track your business',
      text: 'Use your RMA dashboard to keep track of orders, earnings, settlements, offers and other important shop activity.',
    },
    {
      number: 11,
      title: 'Refer other shop owners',
      text: 'Share your permanent RMA referral code with other shop owners and invite them to bring their business online.',
    },
    {
      number: 12,
      title: 'Grow together with RMA',
      text: 'When your referred shop qualifies for the referral program, you can earn a reward based on the RMA fees generated by that shop.',
    },
  ];

  return (
    <div className="how_rma_overlay" onClick={onClose}>
      <div
        className="how_rma_modal"
        onClick={(event) => event.stopPropagation()}
      >
        <div className="how_rma_header">
          <div>
            <span className="how_rma_badge">RMA GROWTH PROGRAM</span>

            <h2>How RMA works</h2>

            <p>
              See how RMA helps a local shop move from offline orders to online
              ordering, delivery, customer growth and more.
            </p>
          </div>

          <button
            type="button"
            className="how_rma_close"
            onClick={onClose}
            aria-label="Close"
          >
            ×
          </button>
        </div>

        <div className="how_rma_steps">
          {steps.map((step, index) => (
            <div
              className={`how_rma_step ${
                index % 2 === 0
                  ? 'how_rma_step_text_first'
                  : 'how_rma_step_image_first'
              }`}
              key={step.number}
            >
              <div className="how_rma_content">
                <span className="how_rma_step_number">
                  {String(step.number).padStart(2, '0')}
                </span>

                <h3>{step.title}</h3>

                <p>{step.text}</p>
              </div>

              <div className="how_rma_visual">
                {step.number === 1 ? (
                  <div className="rma_step_one_visual">
                    <div className="rma_online_signal rma_online_signal_one">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_shop_icon">
                      <span className="rma_shop_roof" />
                      <span className="rma_shop_body">
                        <i />
                        <i />
                      </span>
                    </div>

                    <div className="rma_online_badge">
                      <span className="rma_online_dot" />
                      ONLINE
                    </div>

                    <div className="rma_floating_dot rma_floating_dot_one" />
                    <div className="rma_floating_dot rma_floating_dot_two" />
                    <div className="rma_floating_dot rma_floating_dot_three" />

                    <div className="rma_connection_line" />

                    <RmaCharacter />
                  </div>
                ) : step.number === 2 ? (
                  <div className="rma_step_two_visual">
                    <div className="rma_map">
                      <div className="rma_map_line rma_map_line_one" />
                      <div className="rma_map_line rma_map_line_two" />
                      <div className="rma_map_line rma_map_line_three" />

                      <div className="rma_map_pin rma_map_pin_shop">
                        <span />
                      </div>

                      <div className="rma_map_customer rma_map_customer_one">
                        <span />
                      </div>

                      <div className="rma_map_customer rma_map_customer_two">
                        <span />
                      </div>

                      <div className="rma_map_customer rma_map_customer_three">
                        <span />
                      </div>
                    </div>

                    <div className="rma_discovery_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_discovery_badge">
                      <span className="rma_discovery_dot" />
                      SHOP DISCOVERED
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 3 ? (
                  <div className="rma_step_three_visual">
                    <div className="rma_product_panel">
                      <div className="rma_product_panel_header">
                        <span>My Products</span>
                        <span className="rma_product_add">+</span>
                      </div>

                      <div className="rma_product_card rma_product_card_one">
                        <div className="rma_product_icon">
                          <span />
                        </div>

                        <div className="rma_product_info">
                          <strong>Chicken</strong>
                          <small>₹180 / kg</small>
                        </div>

                        <span className="rma_product_check">✓</span>
                      </div>

                      <div className="rma_product_card rma_product_card_two">
                        <div className="rma_product_icon rma_product_icon_red">
                          <span />
                        </div>

                        <div className="rma_product_info">
                          <strong>Mutton</strong>
                          <small>₹420 / kg</small>
                        </div>

                        <span className="rma_product_check">✓</span>
                      </div>

                      <div className="rma_product_card rma_product_card_three">
                        <div className="rma_product_icon rma_product_icon_dark">
                          <span />
                        </div>

                        <div className="rma_product_info">
                          <strong>Fish</strong>
                          <small>₹280 / kg</small>
                        </div>

                        <span className="rma_product_check">✓</span>
                      </div>

                      <div className="rma_product_add_line">
                        <span>+</span>
                        Add product
                      </div>
                    </div>

                    <div className="rma_product_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 4 ? (
                  <div className="rma_step_four_visual">
                    <div className="rma_order_phone">
                      <div className="rma_order_phone_top">
                        <span>RMA Shop</span>
                        <span className="rma_order_cart">🛒</span>
                      </div>

                      <div className="rma_order_shop_name">Fresh Meat Shop</div>

                      <div className="rma_order_item">
                        <div className="rma_order_item_icon" />

                        <div className="rma_order_item_info">
                          <strong>Chicken</strong>
                          <small>1 kg · ₹180</small>
                        </div>

                        <div className="rma_order_quantity">
                          <span>−</span>
                          <strong>1</strong>
                          <span>+</span>
                        </div>
                      </div>

                      <div className="rma_order_item">
                        <div className="rma_order_item_icon rma_order_item_icon_two" />

                        <div className="rma_order_item_info">
                          <strong>Fish</strong>
                          <small>500 g · ₹140</small>
                        </div>

                        <div className="rma_order_quantity">
                          <span>−</span>
                          <strong>1</strong>
                          <span>+</span>
                        </div>
                      </div>

                      <div className="rma_order_total">
                        <span>Total</span>
                        <strong>₹320</strong>
                      </div>

                      <div className="rma_order_button">PLACE ORDER</div>
                    </div>

                    <div className="rma_order_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 5 ? (
                  <div className="rma_step_five_visual">
                    <div className="rma_new_order_badge">
                      <span className="rma_new_order_dot" />
                      NEW ORDER
                    </div>

                    <div className="rma_order_received_card">
                      <div className="rma_received_header">
                        <div>
                          <span>Order received</span>
                          <strong>#RMA1024</strong>
                        </div>

                        <div className="rma_received_bell">
                          <span />
                        </div>
                      </div>

                      <div className="rma_received_customer">
                        <div className="rma_customer_avatar">
                          <span />
                        </div>

                        <div>
                          <strong>Customer order</strong>
                          <small>2 items · Delivery</small>
                        </div>
                      </div>

                      <div className="rma_received_items">
                        <div>
                          <span>Chicken</span>
                          <strong>1 kg</strong>
                        </div>

                        <div>
                          <span>Fish</span>
                          <strong>500 g</strong>
                        </div>
                      </div>

                      <div className="rma_received_total">
                        <span>Order total</span>
                        <strong>₹320</strong>
                      </div>

                      <div className="rma_accept_button">ACCEPT ORDER</div>
                    </div>

                    <div className="rma_notification_rings">
                      <span />
                      <span />
                      <span />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 6 ? (
                  <div className="rma_step_six_visual">
                    <div className="rma_preparing_order">
                      <div className="rma_preparing_header">
                        <div>
                          <span>ORDER</span>
                          <strong>#RMA1024</strong>
                        </div>

                        <div className="rma_preparing_badge">
                          <span />
                          PREPARING
                        </div>
                      </div>

                      <div className="rma_preparing_items">
                        <div className="rma_preparing_item">
                          <div className="rma_preparing_item_icon">
                            <span />
                          </div>

                          <div className="rma_preparing_item_info">
                            <strong>Chicken</strong>
                            <small>1 kg</small>
                          </div>

                          <span className="rma_item_done">✓</span>
                        </div>

                        <div className="rma_preparing_item">
                          <div className="rma_preparing_item_icon rma_preparing_item_red">
                            <span />
                          </div>

                          <div className="rma_preparing_item_info">
                            <strong>Mutton</strong>
                            <small>500 g</small>
                          </div>

                          <span className="rma_item_done">✓</span>
                        </div>

                        <div className="rma_preparing_item">
                          <div className="rma_preparing_item_icon rma_preparing_item_dark">
                            <span />
                          </div>

                          <div className="rma_preparing_item_info">
                            <strong>Fish</strong>
                            <small>1 kg</small>
                          </div>

                          <span className="rma_item_loading">...</span>
                        </div>
                      </div>

                      <div className="rma_preparing_progress">
                        <div className="rma_preparing_progress_top">
                          <span>Preparing order</span>
                          <strong>75%</strong>
                        </div>

                        <div className="rma_preparing_progress_bar">
                          <div />
                        </div>
                      </div>
                    </div>

                    <div className="rma_preparing_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_preparing_status">
                      <span className="rma_preparing_status_dot" />
                      Order being prepared
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 7 ? (
                  <div className="rma_step_seven_visual">
                    <div className="rma_delivery_order">
                      <div className="rma_delivery_box">
                        <span className="rma_delivery_box_top" />
                        <span className="rma_delivery_box_line" />
                      </div>

                      <strong>ORDER READY</strong>
                    </div>

                    <div className="rma_delivery_route">
                      <span className="rma_route_dot rma_route_dot_one" />
                      <span className="rma_route_dot rma_route_dot_two" />
                      <span className="rma_route_dot rma_route_dot_three" />
                    </div>

                    <div className="rma_delivery_option">
                      <div className="rma_delivery_icon">
                        <span className="rma_bike_body" />
                        <span className="rma_bike_wheel rma_bike_wheel_one" />
                        <span className="rma_bike_wheel rma_bike_wheel_two" />
                        <span className="rma_bike_handle" />
                      </div>

                      <span>DELIVERY</span>
                    </div>

                    <div className="rma_pickup_option">
                      <div className="rma_pickup_icon">
                        <span className="rma_pickup_roof" />
                        <span className="rma_pickup_body" />
                        <span className="rma_pickup_door" />
                      </div>

                      <span>PICKUP</span>
                    </div>

                    <div className="rma_delivery_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 8 ? (
                  <div className="rma_step_eight_visual">
                    <div className="rma_tracking_phone">
                      <div className="rma_phone_top">
                        <span>My Order</span>
                        <span className="rma_phone_signal">●</span>
                      </div>

                      <div className="rma_tracking_status">
                        <span className="rma_tracking_status_dot rma_tracking_status_done">
                          ✓
                        </span>

                        <div>
                          <strong>Order Confirmed</strong>
                          <small>Order received</small>
                        </div>
                      </div>

                      <div className="rma_tracking_line rma_tracking_line_one" />

                      <div className="rma_tracking_status">
                        <span className="rma_tracking_status_dot rma_tracking_status_done">
                          ✓
                        </span>

                        <div>
                          <strong>Preparing</strong>
                          <small>Your order is being prepared</small>
                        </div>
                      </div>

                      <div className="rma_tracking_line rma_tracking_line_two" />

                      <div className="rma_tracking_status">
                        <span className="rma_tracking_status_dot rma_tracking_status_active">
                          •
                        </span>

                        <div>
                          <strong>On the way</strong>
                          <small>Delivery partner is moving</small>
                        </div>
                      </div>
                    </div>

                    <div className="rma_tracking_signal">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_tracking_location">
                      <span className="rma_tracking_location_pin" />
                      <span className="rma_tracking_location_ring" />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 9 ? (
                  <div className="rma_step_nine_visual">
                    <div className="rma_customer_network">
                      <div className="rma_network_shop">
                        <span className="rma_network_shop_roof" />
                        <span className="rma_network_shop_body">
                          <i />
                          <i />
                        </span>

                        <small>YOUR SHOP</small>
                      </div>

                      <div className="rma_customer_node rma_customer_node_one">
                        <span className="rma_customer_head" />
                        <span className="rma_customer_body" />
                      </div>

                      <div className="rma_customer_node rma_customer_node_two">
                        <span className="rma_customer_head" />
                        <span className="rma_customer_body" />
                      </div>

                      <div className="rma_customer_node rma_customer_node_three">
                        <span className="rma_customer_head" />
                        <span className="rma_customer_body" />
                      </div>

                      <div className="rma_customer_node rma_customer_node_four">
                        <span className="rma_customer_head" />
                        <span className="rma_customer_body" />
                      </div>

                      <div className="rma_customer_connection rma_customer_connection_one" />
                      <div className="rma_customer_connection rma_customer_connection_two" />
                      <div className="rma_customer_connection rma_customer_connection_three" />
                      <div className="rma_customer_connection rma_customer_connection_four" />

                      <div className="rma_order_signal rma_order_signal_one">
                        <span>+</span>
                      </div>

                      <div className="rma_order_signal rma_order_signal_two">
                        <span>+</span>
                      </div>

                      <div className="rma_order_signal rma_order_signal_three">
                        <span>+</span>
                      </div>
                    </div>

                    <div className="rma_customer_growth_badge">
                      <span className="rma_growth_badge_dot" />
                      MORE CUSTOMERS
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 10 ? (
                  <div className="rma_step_ten_visual">
                    <div className="rma_dashboard_panel">
                      <div className="rma_dashboard_header">
                        <div>
                          <span>RMA DASHBOARD</span>
                          <strong>Shop Overview</strong>
                        </div>

                        <div className="rma_dashboard_live">
                          <i />
                          LIVE
                        </div>
                      </div>

                      <div className="rma_dashboard_stats">
                        <div className="rma_dashboard_stat">
                          <span className="rma_stat_icon rma_stat_orders">
                            ✓
                          </span>

                          <div>
                            <small>Orders</small>
                            <strong>128</strong>
                          </div>

                          <em>+12%</em>
                        </div>

                        <div className="rma_dashboard_stat">
                          <span className="rma_stat_icon rma_stat_earnings">
                            ₹
                          </span>

                          <div>
                            <small>Earnings</small>
                            <strong>₹24.8K</strong>
                          </div>

                          <em>+8%</em>
                        </div>

                        <div className="rma_dashboard_stat">
                          <span className="rma_stat_icon rma_stat_settlement">
                            ↗
                          </span>

                          <div>
                            <small>Settlements</small>
                            <strong>₹21.4K</strong>
                          </div>

                          <em>Ready</em>
                        </div>

                        <div className="rma_dashboard_stat">
                          <span className="rma_stat_icon rma_stat_offers">
                            ★
                          </span>

                          <div>
                            <small>Offers</small>
                            <strong>₹500</strong>
                          </div>

                          <em>Active</em>
                        </div>
                      </div>

                      <div className="rma_dashboard_activity">
                        <div className="rma_activity_title">
                          <span>Recent activity</span>
                          <small>Today</small>
                        </div>

                        <div className="rma_activity_row">
                          <i />
                          <span>New order received</span>
                          <small>2m</small>
                        </div>

                        <div className="rma_activity_row">
                          <i />
                          <span>Settlement updated</span>
                          <small>8m</small>
                        </div>

                        <div className="rma_activity_row">
                          <i />
                          <span>Offer progress updated</span>
                          <small>14m</small>
                        </div>
                      </div>
                    </div>

                    <div className="rma_dashboard_signal rma_dashboard_signal_one">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_dashboard_signal rma_dashboard_signal_two">
                      <span />
                      <span />
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 11 ? (
                  <div className="rma_step_eleven_visual">
                    <div className="rma_referral_shop rma_referral_shop_sender">
                      <div className="rma_referral_shop_icon">
                        <span className="rma_referral_roof" />
                        <span className="rma_referral_shop_body">
                          <i />
                        </span>
                      </div>

                      <small>YOUR SHOP</small>
                    </div>

                    <div className="rma_referral_code_card">
                      <span className="rma_referral_code_label">
                        RMA REFERRAL CODE
                      </span>

                      <strong>RMA-7K4P9X2Q</strong>

                      <div className="rma_referral_share_icon">
                        <span />
                        <span />
                        <span />
                      </div>
                    </div>

                    <div className="rma_referral_arrow">
                      <span />
                      <span />
                      <span />
                    </div>

                    <div className="rma_referral_shop rma_referral_shop_receiver">
                      <div className="rma_referral_shop_icon">
                        <span className="rma_referral_roof" />
                        <span className="rma_referral_shop_body">
                          <i />
                        </span>
                      </div>

                      <small>NEW SHOP</small>
                    </div>

                    <div className="rma_referral_join_badge">
                      <span>+</span>
                      JOIN RMA
                    </div>

                    <RmaCharacter />
                  </div>
                ) : step.number === 12 ? (
                  <div className="rma_step_twelve_visual">
                    <div className="rma_growth_shop rma_growth_shop_left">
                      <div className="rma_growth_shop_icon">
                        <span className="rma_growth_roof" />
                        <span className="rma_growth_shop_body">
                          <i />
                        </span>
                      </div>

                      <small>YOUR SHOP</small>
                    </div>

                    <div className="rma_growth_center">
                      <div className="rma_growth_circle">
                        <span className="rma_growth_arrow">↗</span>
                      </div>

                      <div className="rma_growth_lines">
                        <span />
                        <span />
                        <span />
                      </div>
                    </div>

                    <div className="rma_growth_shop rma_growth_shop_right">
                      <div className="rma_growth_shop_icon">
                        <span className="rma_growth_roof" />
                        <span className="rma_growth_shop_body">
                          <i />
                        </span>
                      </div>

                      <small>REFERRED SHOP</small>
                    </div>

                    <div className="rma_growth_reward">
                      <span className="rma_growth_reward_star">★</span>

                      <div>
                        <small>RMA REWARD</small>
                        <strong>UP TO ₹500</strong>
                      </div>
                    </div>

                    <div className="rma_growth_success">
                      <span>✓</span>
                      QUALIFIED
                    </div>

                    <RmaCharacter />
                  </div>
                ) : (
                  <div className="how_rma_visual_placeholder">
                    <span>RMA</span>
                    <small>Step {step.number}</small>
                  </div>
                )}
              </div>

              {index < steps.length - 1 && (
                <div className="how_rma_connector" />
              )}
            </div>
          ))}
        </div>

        <div className="how_rma_footer">
          <p>
            Your shop grows. Your customers get a better ordering experience.
            RMA grows with you.
          </p>

          <button
            type="button"
            className="offer_primary_button"
            onClick={onClose}
          >
            <span>Back to Offers</span>
            <span>→</span>
          </button>
        </div>
      </div>
    </div>
  );
}

export default HowRmaWorks;
